require 'rubygems/package_task'

spec = Gem::Specification.new do |s|
  s.platform = Gem::Platform::RUBY
  s.summary = "Simple native extension with .rb/.so name clash used to test dh_ruby"
  s.name = 'simpleextension-with-name-clash'
  s.version = '1.2.3'
  s.requirements << 'none'
  s.require_path = 'ext'
  s.extensions << 'ext/extconf.rb'
  s.author = 'Debian Ruby Extras Maintainers'
  s.email = 'pkg-ruby-extras-maintainers@lists.alioth.debian.org'
  s.homepage = 'https://wiki.debian.org/Teams/Ruby'
  s.license = 'GPL-3+'
  #s.autorequire = 'rake'
  s.files = Dir.glob('{lib,ext,test}/**/*')
  s.description = <<EOF
simpleextension_with_name_clash is a simple native extension that is used to test dh_ruby.
EOF
  s.test_files = ['test/simpleextension_with_name_clash_test.rb']
end

Gem::PackageTask.new(spec) do |pkg|
  pkg.need_zip = false
  pkg.need_tar = false
end
