#!/bin/sh

set -e

basedir="$(readlink -f "$(dirname $0)")"
this_script=$(basename $0)

if [ $# -eq 0 ]; then
  prefix='usage:'
  for program in $(ls -1 ${basedir}/bin); do
    echo "$prefix $this_script $program [ARGS]"
    prefix='      '
  done
  exit 1
fi

export PATH=${basedir}/bin:$PATH
export RUBYLIB=${basedir}/lib
export PERL5LIB=${basedir}/debhelper

"$@"
