require 'rubygems/package_task'

spec = Gem::Specification.new do |s|
  s.platform = Gem::Platform::RUBY
  s.summary = "Simple native extension used to test dh_ruby"
  s.name = 'simpleextension'
  s.version = '1.2.3'
  s.requirements << 'none'
  s.require_path = 'ext'
  s.extensions << 'ext/simpleextension/extconf.rb'
  s.author = 'Debian Ruby Team'
  s.email = 'pkg-ruby-extras-maintainers@lists.alioth.debian.org'
  s.homepage = 'https://wiki.debian.org/Teams/Ruby'
  s.license = 'GPL-3+'
  #s.autorequire = 'rake'
  s.files = Dir.glob('{bin,ext}/**/*')
  s.description = <<EOF
simpleextension is a simple native extension that is used to test dh_ruby.
EOF
  s.test_files = ['test/test_simpleextension.rb']
end

Gem::PackageTask.new(spec) do |pkg|
  pkg.need_zip = false
  pkg.need_tar = false
end
