require 'rubygems'
require 'rake/gempackagetask'

spec = Gem::Specification.new do |s|
  s.platform = Gem::Platform::RUBY
  s.summary = "Simple gem used to test gem2tgz."
  s.name = 'simplegem'
  s.version = '0.0.1'
  s.requirements << 'none'
  s.require_path = 'lib'
  #s.autorequire = 'rake'
  s.files = Dir.glob('lib/**')
  s.description = <<EOF
simplegem is a simple gem that is used to test gem2tgz.
EOF
end

Rake::GemPackageTask.new(spec) do |pkg|
  pkg.need_zip = true
  pkg.need_tar = true
end
