require 'rubygems/package_task'

spec = Gem::Specification.new do |s|
  s.platform = Gem::Platform::RUBY
  s.summary = "Simple program used to test dh_ruby"
  s.name = 'simpleprogram'
  s.version = '1.2.3'
  s.requirements << 'none'
  s.require_path = 'lib'
  s.author = 'Debian Ruby Team'
  s.email = 'pkg-ruby-extras-maintainers@lists.alioth.debian.org'
  s.homepage = 'https://wiki.debian.org/Teams/Ruby'
  s.license = 'GPL-3+'
  #s.autorequire = 'rake'
  s.files = Dir.glob('{bin,man}/**/*')
  s.description = <<EOF
simpleprogram is a simple program that is used to test dh_ruby.
EOF
end

Gem::PackageTask.new(spec) do |pkg|
  pkg.need_zip = false
  pkg.need_tar = false
end
