require 'rubygems'
require 'rake/gempackagetask'

spec = Gem::Specification.new do |s|
  s.platform = Gem::Platform::RUBY
  s.summary = "Simple native extension with extconf.rb in root directory used to test dh_ruby"
  s.name = 'simpleextension_in_root'
  s.version = '1.2.3'
  s.requirements << 'none'
  s.require_path = '.'
  s.extensions << 'extconf.rb'
  #s.autorequire = 'rake'
  s.files = ['extconf.rb', 'simpleextension_in_root.c']
  s.description = <<EOF
simpleextension_in_root is a simple native extension that is used to test
dh_ruby. It contains a Ruby native extension in the root of the source
directory, instead of inside ext/ subdirectory.
EOF
end

Rake::GemPackageTask.new(spec) do |pkg|
  pkg.need_zip = false
  pkg.need_tar = false
end
