require 'rubygems/package_task'

spec = Gem::Specification.new do |s|
  s.platform = Gem::Platform::RUBY
  s.summary = "Library with a fancy name used to test gem2tgz and dh-make-ruby"
  s.name = 'Fancy_Package'
  s.version = '0.0.1'
  s.requirements << 'none'
  s.require_path = 'lib'
  s.author = 'Debian Ruby Team'
  s.email = 'pkg-ruby-extras-maintainers@lists.alioth.debian.org'
  s.homepage = 'https://wiki.debian.org/Teams/Ruby'
  s.license = 'GPL-3+'
  s.files = Dir.glob('lib/**')
  s.description = <<EOF
This package contains two elements of ridiculous upstream names: uppercase
characters and underscores. It is used to make sure gem2tgz and dh-make-ruby
will keep the upstream name intact to be used e.g. in debian/copyright and
debian/watch
EOF
end

Gem::PackageTask.new(spec) do |pkg|
  pkg.need_zip = false
  pkg.need_tar = false
end
